<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import BaseInput from '../common/BaseInput.vue'
import BaseButton from '../common/BaseButton.vue'
import { getTours } from '../../api/tourApi'
import type { TourItem } from '../../types/tour'
import type { PostFormData } from '../../types/board'
import { getTagSuggestions } from '../../repositories/boardRepository'

const props = withDefaults(defineProps<{ initialData?: Partial<PostFormData>; submitLabel: string; loading?: boolean }>(), { initialData: undefined, loading: false })
const emit = defineEmits<{ (e: 'submit', payload: PostFormData): void; (e: 'cancel'): void }>()
const form = reactive<PostFormData>({ title: '', content: '', password: '', region: '', category: 'free', locationType: '', tourContentId: '', tourTitle: '', tourAddress: '', tags: [], existingImages: [], newImages: [] })
const errors = reactive<{ title?: string; content?: string; password?: string; location?: string }>({})
const tagInput = ref(''); const tagSuggestions = ref<string[]>([]); const placeKeyword = ref(''); const placeResults = ref<TourItem[]>([]); const placeLoading = ref(false)
let searchTimer: ReturnType<typeof setTimeout> | undefined
watch(() => props.initialData, (data) => { const value = data ?? {}; Object.assign(form, { ...form, ...value, password: '', tags: value.tags ?? [], existingImages: value.existingImages ?? [], newImages: [], locationType: value.locationType ?? '', tourContentId: value.tourContentId ?? '', tourTitle: value.tourTitle ?? '', tourAddress: value.tourAddress ?? '' }) }, { immediate: true, deep: true })
const loadPlaces = async (keyword = '') => { placeLoading.value = true; try { placeResults.value = (await getTours({ page: 1, size: 20, keyword: keyword || undefined })).items } finally { placeLoading.value = false } }
const searchPlaces = () => { if (searchTimer) clearTimeout(searchTimer); searchTimer = setTimeout(() => loadPlaces(placeKeyword.value.trim()), 300) }
const selectPlace = (place: TourItem) => { form.locationType = 'tour'; form.tourContentId = place.id; form.tourTitle = place.title; form.tourAddress = place.address; placeResults.value = []; placeKeyword.value = ''; errors.location = undefined }
const resetPlace = () => { form.locationType = ''; form.tourContentId = ''; form.tourTitle = ''; form.tourAddress = ''; placeKeyword.value = ''; void loadPlaces() }
const selectNoLocation = () => { form.locationType = 'none'; form.tourContentId = ''; form.tourTitle = ''; form.tourAddress = ''; placeResults.value = []; placeKeyword.value = ''; errors.location = undefined }
const addTag = () => { const tag = tagInput.value.trim().replace(/^#/, ''); if (tag && !form.tags.includes(tag) && form.tags.length < 10) form.tags.push(tag); tagInput.value = ''; tagSuggestions.value = [] }
const loadTagSuggestions = async () => { const keyword = tagInput.value.trim(); tagSuggestions.value = keyword ? (await getTagSuggestions(keyword)).map((tag) => tag.name) : [] }
const addImages = (event: Event) => { const files = Array.from((event.target as HTMLInputElement).files ?? []); form.newImages = [...form.newImages, ...files].slice(0, 5 - form.existingImages.length) }
const submit = () => { errors.title = form.title.trim() ? undefined : '제목을 입력해 주세요.'; errors.content = form.content.trim() ? undefined : '내용을 입력해 주세요.'; errors.password = form.password.trim() ? undefined : '비밀번호를 입력해 주세요.'; errors.location = form.locationType && (form.locationType === 'none' || form.tourContentId) ? undefined : '관광지 또는 지역 없음을 선택해 주세요.'; if (!errors.title && !errors.content && !errors.password && !errors.location) emit('submit', { ...form, title: form.title.trim(), content: form.content.trim() }) }
</script>

<template>
  <form class="mx-auto max-w-3xl space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8" @submit.prevent="submit">
    <div class="border-b border-slate-100 pb-4"><h2 class="text-lg font-semibold text-slate-900">게시글 작성</h2><p class="mt-1 text-sm text-slate-500">별표(*) 항목은 필수입니다.</p></div>
    <div><label class="mb-2 block text-sm font-semibold text-slate-800">제목 <span class="text-rose-500">*</span></label><BaseInput v-model="form.title" placeholder="제목을 입력해 주세요" :disabled="props.loading" /><p v-if="errors.title" class="mt-2 text-sm text-rose-500">{{ errors.title }}</p></div>
    <div><label class="mb-2 block text-sm font-semibold text-slate-800">내용 <span class="text-rose-500">*</span></label><textarea v-model="form.content" class="min-h-[220px] w-full rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-sky-400 focus:ring-2 focus:ring-sky-100" placeholder="여행에서 경험한 이야기를 자유롭게 적어 주세요." :disabled="props.loading" /><p v-if="errors.content" class="mt-2 text-sm text-rose-500">{{ errors.content }}</p></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-semibold text-slate-800">관광지 <span class="text-rose-500">*</span></label><div class="relative rounded-xl border border-slate-200 bg-slate-50 p-3"><template v-if="form.locationType === 'none'"><p class="font-medium text-slate-800">지역 없음</p><button type="button" class="mt-2 text-sm text-sky-700" @click="resetPlace">관광지 선택하기</button></template><template v-else-if="form.tourContentId"><p class="font-semibold text-slate-800">{{ form.tourTitle }}</p><p class="mt-1 text-xs text-slate-500">{{ form.tourAddress }}</p><button type="button" class="mt-2 text-sm text-sky-700" @click="resetPlace">다시 선택</button></template><template v-else><BaseInput v-model="placeKeyword" placeholder="관광지 이름 또는 주소 검색" @focus="loadPlaces()" @update:model-value="searchPlaces" /><div class="mt-2 flex items-center justify-between"><button type="button" class="text-xs text-slate-500 hover:text-sky-700" @click="selectNoLocation">지역 없음으로 작성</button><span v-if="placeLoading" class="text-xs text-sky-600">검색 중...</span></div><div v-if="placeResults.length" class="absolute left-0 right-0 top-full z-20 mt-2 max-h-56 space-y-1 overflow-y-auto rounded-xl border border-slate-200 bg-white p-2 shadow-lg"><button v-for="place in placeResults" :key="place.id" type="button" class="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-sky-50" @click="selectPlace(place)"><strong>{{ place.title }}</strong><span class="mt-1 block truncate text-xs text-slate-500">{{ place.address || '주소 정보 없음' }}</span></button></div></template></div><p v-if="errors.location" class="mt-2 text-sm text-rose-500">{{ errors.location }}</p></div><div><label class="mb-2 block text-sm font-semibold text-slate-800">카테고리</label><select v-model="form.category" class="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-700 outline-none focus:border-sky-400 focus:ring-2 focus:ring-sky-100"><option value="free">자유</option><option value="question">질문</option><option value="recommendation">추천</option></select></div></div>
    <div><label class="mb-2 block text-sm font-semibold text-slate-800">태그</label><div class="flex gap-2"><BaseInput v-model="tagInput" placeholder="태그 입력" @update:model-value="loadTagSuggestions" @keydown.enter.prevent="addTag" /><BaseButton type="button" variant="secondary" @click="addTag">추가</BaseButton></div><div v-if="tagSuggestions.length" class="mt-2 flex flex-wrap gap-1"><button v-for="tag in tagSuggestions" :key="tag" type="button" class="rounded-lg bg-slate-100 px-2 py-1 text-xs" @click="tagInput = tag; addTag()">#{{ tag }}</button></div><div class="mt-3 flex flex-wrap gap-2"><button v-for="tag in form.tags" :key="tag" type="button" class="rounded-full bg-sky-50 px-3 py-1.5 text-sm text-sky-700" @click="form.tags = form.tags.filter((item) => item !== tag)">#{{ tag }} ×</button></div></div>
    <div><label class="mb-2 block text-sm font-semibold text-slate-800">이미지</label><input class="block w-full rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-sm" type="file" accept="image/jpeg,image/png,image/webp" multiple :disabled="props.loading" @change="addImages" /><div class="mt-3 flex flex-wrap gap-2"><button v-for="image in form.existingImages" :key="image.id" type="button" @click="form.existingImages = form.existingImages.filter((item) => item.id !== image.id)"><img :src="image.url" :alt="image.original_name" class="h-16 w-16 rounded-xl object-cover" /></button><span v-for="file in form.newImages" :key="file.name" class="rounded-lg bg-slate-100 px-2 py-1 text-xs text-slate-600">{{ file.name }}</span></div></div>
    <div><label class="mb-2 block text-sm font-semibold text-slate-800">비밀번호 <span class="text-rose-500">*</span></label><BaseInput v-model="form.password" type="password" placeholder="수정·삭제에 사용할 비밀번호" :disabled="props.loading" /><p v-if="errors.password" class="mt-2 text-sm text-rose-500">{{ errors.password }}</p></div>
    <div class="flex flex-col-reverse gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:justify-end"><BaseButton type="button" variant="secondary" :disabled="props.loading" @click="emit('cancel')">취소</BaseButton><BaseButton type="submit" :disabled="props.loading">{{ props.loading ? '등록 중...' : props.submitLabel }}</BaseButton></div>
  </form>
</template>

<style scoped>
div[class~="max-h-56"] {
  max-height: 14rem !important;
  overflow-y: scroll !important;
}
</style>
